# Generated by Django 5.1.6 on 2025-02-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0010_alter_booking_booking_id_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default='727110ad38', max_length=200, unique=True),
        ),
    ]
