# Generated by Django 5.1.6 on 2025-02-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0013_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor'), ('admin', 'Admin')], default='user', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('profile', 'total', 'payment')},
        ),
    ]
