# Generated by Django 5.1.6 on 2025-02-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0016_bookingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='products',
            field=models.ManyToManyField(to='grocery.product'),
        ),
    ]
