# Generated by Django 5.1.6 on 2025-02-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0017_booking_products'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
