# Generated by Django 5.1.6 on 2025-02-23 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0018_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('profile', 'total', 'payment')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='products',
        ),
    ]
