# Generated by Django 5.1.6 on 2025-02-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0021_remove_cart_quantity_booking_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='products',
            field=models.ManyToManyField(to='grocery.product'),
        ),
    ]
